### ISSUE TITLE
No description about how to setup an External Template

### ISSUE THREAD

**Issue by adaliszk** [SteffTek/swf-dev-kit#1]
Hi, I am trying to use your plugin to serve a simple HTML website but I could not make the Template example work. Could you extend the description of how to use an External template?

**Comment by SteffTek** [comment]
Im Sorry for the missing information. You have to create a folder (WebBuilder/Templates/FOLDER). Inside you place your template.json and your linked HTML File. The name you set up in the JSON is the name you place inside your WebBuilder. Please keep me updated if you have issues.

**Comment by adaliszk** [comment]
Awesome works nicely. I'll leave this issue open for you to add it to the README :)
