### ISSUE TITLE
Wordpress to SWF

### ISSUE THREAD

**Issue by bugram** [SteffTek/swf-dev-kit#3]
I have wordpress website in local and I dont know how to make website without gui webpage builders.

I use simply static plugin to export pages as index.html page by page, uploaded to WebServer folder and ofc it didnt work.
Can you make some implementation for simply static plugin? What am i missing?

Thanks...

**Comment by SteffTek** [comment]
Hey!

Can you please upload your Plugin folder as zip? Usually static websites should be served just fine if placed in the WebServer folder.

Thx!

**Comment by SteffTek** [comment]
I added a new Config Option for default pages. You need to set it to your default .html file (probably index.html).

I also extended the documentation :)

**Comment by SteffTek** [comment]
@bugram Got any Update for me?

**Comment by bugram** [comment]
worked fine thank you sorry for inconvenience :) (i was doing wrong to put in assets or sth)

**Comment by SteffTek** [comment]
@bugram Well, at least I added in the option for default page links :D But thanks for the response <3
